# Generated by Django 5.0.4 on 2024-04-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_dni_note_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
    ]
