# Generated by Django 5.0.4 on 2024-05-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='especialidad',
            field=models.CharField(default='', max_length=100),
        ),
    ]
